''' Default configurations '''
MQTT_BROCKER_HOST = '192.168.0.10'
MQTT_BROCKER_PORT = 1883
MQTT_KEEP_ALIVE = 60
MQTT_TOPIC_WATER_METER = 'sensors/water/meter'
MQTT_INTERVAL_WATER_METER = 2
MQTT_TOPIC_WATER_TANK = 'sensors/water/tank'
MQTT_INTERVAL_WATER_TANK = 2
